<?php

namespace DREAMHOTEL\ActivitesBundle\Repository;

/**
 * acceuilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class acceuilRepository extends \Doctrine\ORM\EntityRepository
{
}
