<?php

namespace DREAMHOTEL\ActivitesBundle\Repository;

/**
 * activitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class activitesRepository extends \Doctrine\ORM\EntityRepository
{
}
