<?php

namespace DREAMHOTEL\ChambresBundle\Repository;

/**
 * chambresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chambresRepository extends \Doctrine\ORM\EntityRepository
{
}
