<?php

namespace DREAMHOTEL\ChambresBundle\Repository;

/**
 * typeChambreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeChambreRepository extends \Doctrine\ORM\EntityRepository
{
}
