DREAMHOTEL\ActivitesBundle\Entity\acceuil:
    type: entity
    table: null
    repositoryClass: DREAMHOTEL\ActivitesBundle\Repository\acceuilRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libelle:
            type: string
            length: '30'
        prix:
            type: decimal
            precision: '4'
            scale: '4'
    lifecycleCallbacks: {  }
