dreamhotel_accueil:
    path:     /
    defaults: { _controller: DREAMHOTELAccueilBundle:Default:index }
    
dreamhotel_chambres:
   path: /chambres
   defaults: { _controller: DREAMHOTELChambresBundle:Default:index }
   
dreamhotel_salles:
   path: /salles
   defaults: { _controller: DREAMHOTELSallesBundle:Default:index }
    
    
dreamhotel_evenements:    
   path: /evenements
   defaults: { _controller: DREAMHOTELEvenementsBundle:Default:index }
  
dreamhotel_activites:
   path: /activites
   defaults: { _controller: DREAMHOTELActivitesBundle:Default:index}
    
dreamhotel_reserver:
   path: /reserver
   defaults: { _controller: DREAMHOTELReserverBundle:Default:index}

dreamhotel_creercompte:
   path: /creer_compte
   defaults: { _controller: DREAMHOTELCompteBundle:Default:creercompte}