<?php

namespace DREAMHOTEL\SallesBundle\Repository;

/**
 * sallesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sallesRepository extends \Doctrine\ORM\EntityRepository
{
}
