<?php

namespace DREAMHOTEL\CompteBundle\Repository;

/**
 * evaluerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class evaluerRepository extends \Doctrine\ORM\EntityRepository
{
}
